M48
; DRILL file {KiCad 9.0.0} date 2025-06-14T22:04:37-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-14T22:04:37-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X5.3415Y-3.0226
X5.5325Y-3.0226
T2
X5.3297Y-2.9033
X5.5443Y-2.9033
T3
X4.34Y-2.94
X4.34Y-5.46
X6.16Y-2.94
X6.16Y-5.46
M30
